---
- name:  Windows Commands 
  hosts: windows
  gather_facts: false
  tasks:
    - name: run an executable using win_command
      win_command: whoami.exe
    - name: run a command under PowerShell
      win_shell: Get-Service > C:\temp\command.txt 
